# Dependencies
markdown:         kramdown
highlighter:         true

# Permalinks
permalink:        pretty

excerpt_separator: "<!--more-->"

# Setup
title:            Prem Seetharaman
tagline:          ''
description:      '
  I am a PhD candidate at Northwestern University in the 
  <a href="http://music.cs.northwestern.edu">Interactive Audio Lab</a>, 
  under Prof. Bryan Pardo. 
  The objective of my research is to create machines that can 
  understand the auditory world like humans can.
  I work in machine learning, music information retrieval, 
  audio source separation, music structure and similarity, acoustics, and human
  computer interaction.
'

cv:
  link: /public/cv.pdf

paginate:		10
plugins: [jekyll-paginate, jekyll-picture-tag]
baseurl: ""
picture:
  source: public/images/
  output: public/generated/
  markup: picture
  presets:
    # Full width pictures
    default:
      ppi: [1, 1.5]
      attr:
        class: center-image
        itemprop: image
      source_lrg:
        media: "(min-width: 40em)"
        width: 700
      source_med:
        media: "(min-width: 30em)"
        width: 450
      source_default:
        width: 350
        height: 200
    # Half width pictures
    half:
      ppi: [1, 1.5]
      attr:
        class: center-image
        data-location: "{{location}}"
        data-active: nil
      source_lrg:
        media: "(min-width: 40em)"
        width: 400
      source_med:
        media: "(min-width: 30em)"
        width: 250
      source_default:
        width: 350
    # Self-set resolution sources. Useful if you don't want a 1:1 image size to dppx ratio.
    gallery:
      attr:
        class: center-image
      source_wide_hi:
        media: "(min-width: 40em) and (min-resolution: 1.5dppx)"
        width: 900
        height: 600
      source_wide:
        media: "(min-width: 40em)"
        width: 600
        height: 400
      source_default:
        width: 250
        height: 250
