---
title: Prem Seetharaman
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
markdown: kramdown
highlighter: true
permalink: pretty
excerpt_separator: "<!--more-->"
tagline: ''
description: ' I am a teaching fellow at Northwestern University. I recieved my PhD
  in 2019, advised by <a href="https://users.cs.northwestern.edu/~pardo/">Bryan Pardo</a>.
  The objective of my research is to create machines that can understand the auditory
  world. I work in computer audition, machine learning, and human computer interaction. '
sass:
  sass_dir: assets/css
cv:
  link: "/public/cv.pdf"
scholar:
  style: apa
  locale: en
  sort_by: year
  order: descending
  bibliography_list_tag: p
  bibliography_item_tag: p
  source: "./_data"
  bibliography: publications.bib
  bibliography_template: bib
  replace_strings: false
  query: "@*"
paginate: 10
plugins:
- jekyll-paginate
- jekyll-picture-tag
baseurl: ''
picture:
  source: public/images/
  output: public/generated/
  markup: picture
  presets:
    default:
      ppi:
      - 1
      - 1.5
      attr:
        class: center-image
        itemprop: image
      source_lrg:
        media: "(min-width: 40em)"
        width: 700
      source_med:
        media: "(min-width: 30em)"
        width: 450
      source_default:
        width: 350
        height: 200
    half:
      ppi:
      - 1
      - 1.5
      attr:
        class: center-image
        data-location: "{{location}}"
        data-active: nil
      source_lrg:
        media: "(min-width: 40em)"
        width: 400
      source_med:
        media: "(min-width: 30em)"
        width: 250
      source_default:
        width: 350
    gallery:
      attr:
        class: center-image
      source_wide_hi:
        media: "(min-width: 40em) and (min-resolution: 1.5dppx)"
        width: 900
        height: 600
      source_wide:
        media: "(min-width: 40em)"
        width: 600
        height: 400
      source_default:
        width: 250
        height: 250
